[[strategies]]
name = "Bullish reversal"
type = "Long"

[strategies.patterns]
m5 = "2D-1-2U"
m15 = "2U"
d = "2U"

[strategies.tfc]
m60 = "G"
d = "G"
w = "G"

[strategies.exit]
type = "counter-reversal"
m5 = "2U-1-2D"


[[strategies]]
name = "Bullish reversal simple"
type = "Long"

[strategies.patterns]
m5 = "2D-1-2U"
d = "2U"

[strategies.tfc]
m60 = "G"
d = "G"
w = "G"

[strategies.exit]
type = "counter-reversal"
m5 = "2U-1-2D"


[[strategies]]
name = "Bearish reversal simple"
type = "Short"

[strategies.patterns]
m5 = "2U-1-2D"
d = "2D"

[strategies.tfc]
m60 = "R"
d = "R"
w = "R"

[strategies.exit]
type = "counter-reversal"
m5 = "2D-1-2U"


[[strategies]]
name = "Bullish reversal 2-2"
type = "Long"

[strategies.patterns]
m5 = "2U-2D"
d = "2U"

[strategies.tfc]
m60 = "G"
d = "G"
w = "G"

[strategies.exit]
type = "counter-reversal"
m5 = "2D-2U"


[paths]
logs = '''/Users/sepy/Library/Mobile\ Documents/com\~apple\~CloudDocs/logs/'''