[[strategies]]
name = "Weighted strat"
type = "Long"

[strategies.weights]
1h = 1
1d = 1
1w = 1
1m = 1

[strategies.penalties]
1h = -1
1d = -2
1w = -3
1m = -4

[strategies.exit]
type = "counter-trend"
1h = -1

[strategies.tfc]
# TODO: not quite sure what to have here



[paths]
logs = '''/Users/sepy/Library/Mobile\ Documents/com\~apple\~CloudDocs/logs/'''