#[[strategies]]
#name = "Weighted strat"
#type = "Long"
#threshold = 3

#[strategies.weights]
#m60 = 1
#d = 1
#w = 1
#m = 1

#[strategies.penalties]
#m60 = -1
#d = -2
#w = -3
#m = -4

#[strategies.exit]
#type = "counter-trend"
#m60 = -1

#[strategies.tfc]
# TODO: not quite sure what to have here

[[strategies]]
name = "Simple trend"
type = "Long"
threshold = 3

[strategies.weights]
d = 1
w = 1
m = 1

[strategies.penalties]
d = -1
w = -1
m = -1

[strategies.exit]
type = "counter-trend"
d = -1

[strategies.tfc]
# TODO: not quite sure what to have here



[paths]
logs = '''/Users/sepy/Library/Mobile\ Documents/com\~apple\~CloudDocs/logs/'''